test:
  quiet: true
  dry_run: false
  dry_run_email: test@mail.com
  base_uri: http://test.ruslanledesma.com
  feed: http://ruslanledesma.com/feed.xml # reset by env for end-to-end test
  unsubscribe_uri: 'http://newsletter.ruslanledesma.com/unsubscribe/?email=<%= recipient %>'
  confirmation_uri: http://newsletter.ruslanledesma.com/unsubscribed/
  subject: 'Test <%= title %> - <%= date %>'
  from: '<%= title %> <no-reply@ruslanledesma.com>'
  html_template: templates/test.html.erb
  plain_template: templates/test.txt.erb
  smtp_host: localhost # reset by env for end-to-end test
  smtp_port: 25 # reset by env for end-to-end test
  smtp_user:
  smtp_pass:
  smtp_auth:
  smtp_ttls: false

development: &dev
  quiet: false
  dry_run: false
  dry_run_email: your.email@mail.com
  base_uri: http://newsletter.ruslanledesma.com
  feed: http://ruslanledesma.com/feed.xml
  unsubscribe_uri: 'http://ruslanledesma.com/unsubscribe/?email=<%= recipient %>'
  confirmation_uri: http://ruslanledesma.com/unsubscribed/
  subject: '<%= title %>: newsletter for <%= date %>'
  from: '<%= title %> <no-reply@ruslanledesma.com>'
  html_template: templates/production.html.erb
  plain_template: templates/production.txt.erb
  smtp_host:
  smtp_port:
  smtp_user:
  smtp_pass:
  smtp_auth:
  smtp_ttls:

production:
  <<: *dev
